#!/bin/sh
option=$(echo 'Shutdown
Reboot
Lock
Logout' | rofi -dmenu -l 4 -p Power menu)
if [ "$option" = "" ]; then exit 1; fi

sure=$(echo 'yes
no' | rofi -dmenu -l 2 -p "Are you sure?")
if [ "$sure" != "yes" ]; then exit 1; fi

case $option in
	Shutdown) shutdown now;;
	Reboot) reboot;;
	Lock) i3lock -ti ~/pix/wallpaper/feintile.png;;
	Logout) i3-msg exit;; 
esac
