#!/bin/sh
off=`amixer get Master | grep off | wc -l`
case $off in
0)
 echo `amixer get Master | grep -Eo '[0-9]{1,3}?%' | head -1 | awk '{print "", $0}'`
;;
*)
echo `amixer get Master | grep -Eo '[0-9]{1,3}?%' | head -1 | awk '{print "", $0}'`
;;
esac
