#!/bin/bash
result=$(curl -Ss 'https://wttr.in?0&T&Q' | cut -c 16- | head -2 | xargs echo)
cloud=$(echo "$result" | grep -Eic "cloud|fog|overcast")
sun=$(echo "$result" | grep -Eic "clear|sun")
snow=$(echo "$result" | grep -Eic "snow|sleet")
rain=$(echo "$result" | grep -Eic "rain|drizzle")
storm=$(echo "$result" | grep -Eic "storm|thunder") 
wind=$(echo "$result" | grep -ic wind)
dead=$(echo "$result" | grep -c "°")
[[ "$dead" = 0 ]] && exit 1
[[ "$cloud" = 1 ]] && icon=""
[[ "$sun" = 1 ]] && icon=""
[[ "$snow" = 1 ]] && icon=""
[[ "$rain" = 1 ]] && icon=""
[[ "$storm" = 1 ]] && icon=""
[[ "$wind" = 1 ]] && icon=""
echo "$icon $result"
